/** Central UI copy — English for now; swap for i18n later */
export const DEFAULT_PROFILE_NAME = 'Music Lover';

export function hasCustomProfileName(name: string): boolean {
  return name.trim().toLowerCase() !== DEFAULT_PROFILE_NAME.toLowerCase();
}

export const strings = {
  songMenu: {
    playNext: 'Play next',
    addToQueue: 'Add to queue',
    startRadio: 'Start radio',
    addToPlaylist: 'Add to playlist',
    favorite: 'Favorite',
    removeFavorite: 'Remove favorite',
    goToArtist: 'Go to artist',
    removeFromPlaylist: 'Remove from this playlist',
    removeFromQueue: 'Remove from queue',
    comingSoon: 'Coming soon',
    radioStarted: (artist: string) => `Radio · ${artist}`,
    newPlaylist: 'New playlist',
    searchPlaceholder: 'Search playlists',
    moreOptions: 'More options',
    closePlaylistSubmenu: 'Close playlist submenu',
    menuLabel: (title: string) => `${title} menu`,
    addedToQueue: 'Added to queue',
    alreadyInQueue: 'Already in queue',
    playingNext: 'Playing next',
    addedTo: (name: string) => `Added to ${name}`,
    addedToFavorites: 'Added to favorites',
    removedFromFavorites: 'Removed from favorites',
    removedFromQueue: 'Removed from queue',
    undo: 'Undo',
  },
  toast: {
    couldNotPlay: 'Could not play track',
    noStreamForTrack: (title: string) => `No stream found for "${title}". Try searching directly.`,
    playbackError: 'Playback error',
    streamUnavailable: 'Could not retrieve the audio stream.',
    alreadyInQueue: 'Already in queue',
    noReleasesFound: 'No releases found',
    noReleasesForArtist: (artist: string) => `Could not find releases for ${artist}.`,
    couldNotLoadArtist: 'Could not load artist',
    couldNotFetchArtist: (artist: string) => `Could not fetch releases for ${artist}.`,
    invalidArtist: 'Invalid artist',
    couldNotLoadLink: 'Could not load link',
    checkUrlAndRetry: 'Check the URL and try again.',
    queueEmpty: 'Queue is empty',
    queueEmptyDesc: 'Add songs to keep playing.',
  },
  search: {
    navLabel: 'Search',
    keyboardHint: '↑↓ navigate · Enter open · Esc clear',
  },
  compact: {
    openNowPlaying: 'Now playing',
    closeNowPlaying: 'Close now playing',
    upNext: 'Up next',
    upNextOpen: 'Viewing up next',
    showUpNext: 'Show up next',
    hideUpNext: 'Hide up next',
  },
  queue: {
    upNext: 'Up Next',
    emptyTitle: 'Nothing queued yet',
    emptyHint: 'Search above to add tracks',
    emptyHintWithLikes: 'Search above, or quick-add from your likes below',
    searchPlaceholder: 'Search or paste a link...',
    noResults: 'No results found',
    pressEnter: 'Press Enter to search',
    playlistEmpty: 'This playlist is empty',
    library: {
      playlists: 'No playlists found. Create them in My Hub!',
      artists: 'No artists resolved yet.',
      likes: 'No favorites saved yet.',
    },
  },
  artist: {
    label: 'Artist',
    loading: 'Finding songs…',
    songCount: (n: number) => (n === 1 ? '1 song' : `${n} songs`),
    play: 'Play',
    shuffle: 'Shuffle',
    startRadio: 'Start radio',
    popular: 'Popular',
    latestRelease: 'Latest release',
    latestSingle: 'Latest single',
    latestAlbum: 'Latest album',
    latestEp: 'Latest EP',
    discography: 'Discography',
    filterAll: 'All',
    filterAlbums: 'Albums',
    filterSingles: 'Singles & EPs',
    album: 'Album',
    single: 'Single',
    ep: 'EP',
    playAlbum: 'Play release',
    fansAlsoLike: 'Fans also like',
    aboutArtist: (name: string) => `About ${name}`,
    readMore: 'Read more',
    readLess: 'Read less',
    sourcePrefix: 'Source:',
    sourceLastFm: 'Last.fm',
    sourceWikipedia: 'Wikipedia',
    discographySummary: (albums: number, singles: number) => {
      const parts: string[] = [];
      if (albums > 0) parts.push(albums === 1 ? '1 album' : `${albums} albums`);
      if (singles > 0) parts.push(singles === 1 ? '1 single' : `${singles} singles & EPs`);
      return parts.join(' · ');
    },
    showAll: (n: number) => `Show all ${n}`,
    showLess: 'Show less',
    empty: 'No songs found for this artist yet.',
    listenersCount: (n: number) => {
      const formatted = n >= 1_000_000 ? `${(n / 1_000_000).toFixed(1).replace(/\.0$/, '')}M` : n >= 10_000 ? `${Math.round(n / 1_000)}k` : n.toLocaleString('en-US');
      return `${formatted} listeners`;
    },
    metaWithListeners: (listeners: number, songs: number) => {
      const formatted = listeners >= 1_000_000 ? `${(listeners / 1_000_000).toFixed(1).replace(/\.0$/, '')}M` : listeners >= 10_000 ? `${Math.round(listeners / 1_000)}k` : listeners.toLocaleString('en-US');
      return `${formatted} listeners · ${songs === 1 ? '1 song' : `${songs} songs`}`;
    },
    whichArtist: 'Which artist?',
    whichArtistHint: 'A few artists share this name — pick the right one.',
    openProfile: 'Artist',
    openProfileNamed: (name: string) => `Open ${name}`,
  },
  home: {
    continue: 'Continue',
    nowPlaying: 'Now playing',
    jumpBackIn: 'Jump back in',
    yourMixes: 'Your mixes',
    yourLibrary: 'Your library',
    favorites: 'Favorites',
    artists: 'Artists you play',
    playMix: 'Play mix',
    coldStartEyebrow: 'First listen',
    coldStartTitle: 'Pick 3 artists you love',
    coldStartBody: 'We’ll use them to build your Home — mixes, Discover, and Your sound.',
    coldStartSearch: 'Search artists',
    coldStartSuggestions: 'From the charts',
    coldStartProgress: (n: number, max: number) => `${n} of ${max}`,
    coldStartConfirm: 'Start listening',
    coldStartSeeding: 'Building your taste…',
    coldStartBrowse: 'Browse Discover instead',
    coldStartNoHits: 'No artists matched. Try another spelling.',
    coldStartChartsEmpty: 'Charts are slow right now — search for three artists you love.',
  },
  library: {
    favoritesSortLabel: 'Sort by',
    favoritesSortRecent: 'Recently added',
    favoritesSortTitle: 'Title',
    favoritesSortArtist: 'Artist',
    favoritesDateAdded: 'Date added',
  },
  radio: {
    starting: 'Starting radio…',
    started: (artist: string) => `Playing radio · ${artist}`,
    empty: 'Couldn’t find similar songs for radio.',
    failed: 'Radio couldn’t start. Try another track.',
  },
  settings: {
    autoplay: 'Autoplay',
    autoplayDesc: 'When the queue is almost empty',
    autoplayAsk: 'Ask',
    autoplayOn: 'Always',
    autoplayOff: 'Off',
  },
  nextUp: {
    title: 'Next up',
    headerTitle: (n: number) => `Next up · ${n}`,
    shuffle: 'Shuffle',
    clear: 'Clear',
    queueCleared: 'Queue cleared',
    playingFrom: (source: string) => `Playing from ${source}`,
    queueEndsSoon: 'Queue ends soon',
    queueEndsSoonDesc: 'More like this, picked from what’s playing',
    keepPlaying: 'Keep playing',
    notNow: 'Not now',
    keepPlayingStarted: 'Playing more like this',
    keepPlayingAlways: 'Always',
    keepPlayingAlwaysOn: 'NOIR will keep playing. Change it in Settings.',
    emptyTitle: 'Nothing up next',
    emptyFromFavorites: 'Keep going with your favorites?',
    emptyFromRecents: 'Pick up where you left off?',
    emptyNothing: 'Find something new in Discover.',
    addBatch: (n: number) => `Add ${n}`,
    shuffleAll: 'Shuffle all',
    browseDiscover: 'Browse Discover',
    addOne: (title: string) => `Add ${title} to queue`,
    addedOne: 'Added to queue',
    addedMany: (n: number) => (n === 1 ? 'Added 1 song to queue' : `Added ${n} songs to queue`),
    undo: 'Undo',
  },
  lyrics: {
    title: 'Lyrics',
    loading: 'Finding lyrics…',
    empty: 'No lyrics found',
    emptyHint: 'Enjoy the music instead.',
    show: 'Show lyrics',
    hide: 'Hide lyrics',
    unavailable: 'No lyrics for this song',
    instrumental: 'Instrumental',
  },
  error: {
    brand: 'NOIR',
    title: 'Something broke',
    body: 'The UI hit a snag. Music might still be playing — reload, or try to recover.',
    reload: 'Reload',
    recover: 'Try to recover',
    persist: 'Still stuck? Hard-refresh the tab.',
  },
  nowPlaying: {
    playingFrom: (source: string) => `Playing from ${source}`,
    openSource: 'Open source',
    hideSide: 'Hide side panel',
    showSide: 'Show side panel',
  },
  playlist: {
    label: 'Playlist',
    back: 'Library',
    newPlaylist: 'New playlist',
    songCount: (n: number) => (n === 1 ? '1 song' : `${n} songs`),
    play: 'Play',
    playAll: 'Play all',
    shuffle: 'Shuffle',
    more: 'More',
    rename: 'Rename',
    delete: 'Delete playlist',
    renameHint: 'Click to rename',
    removeFromPlaylist: 'Remove from this playlist',
    dragToReorder: 'Drag to reorder',
    emptyTitle: "Let's fill this up",
    emptyBody: 'Search for songs, or add some you already love.',
    addSongs: 'Add songs',
    close: 'Close',
    emptyRow: 'No songs yet.',
    emptyWithPanel: 'No songs yet. Pick some on the right.',
    tabFavorites: 'Favorites',
    tabRecents: 'Recently played',
    noFavorites: 'No favorites yet. Search instead.',
    noRecents: 'Nothing played yet. Search instead.',
    searchPlaceholder: 'Search songs to add',
    searching: 'Searching…',
    noResults: (q: string) => `Nothing for “${q}”.`,
    suggested: 'From your favorites',
    add: 'Add',
    added: 'Added',
    addedTo: (name: string) => `Added to ${name}`,
    removedFrom: (name: string) => `Removed from ${name}`,
    deleted: 'Playlist deleted',
    undo: 'Undo',
    libraryCount: (n: number) => (n === 1 ? '1 playlist' : `${n} playlists`),
    libraryEmptyTitle: 'No playlists yet',
    libraryEmptyBody: 'Make one for a mood, a moment, or a person.',
  },
  empty: {
    favoritesTitle: 'No favorite songs yet',
    favoritesDesc: 'Tap the heart on a track, in the player bar, or while searching to save it here.',
    favoritesAction: 'Browse Discover',
    playlistEmptyTitle: 'This playlist is empty',
    playlistEmptyDesc: 'Search below to find and add tracks.',
    noPlaylistsTitle: 'No playlists yet',
    noPlaylistsDesc: 'Click "Create New" to start your first collection.',
    noRecentsTitle: 'No recent songs',
    noRecentsDesc: 'Start playing tracks to fill your recents history.',
    noArtistsTitle: 'No artists yet',
    noArtistsDesc: 'Your recently played artists will show up here.',
    noPlaylistsOverviewTitle: 'No playlists created yet',
    noPlaylistsOverviewDesc: 'Go to the Playlists tab to create collections.',
    goToPlaylists: 'Go to Playlists',
  },
  discover: {
    trendingUnavailable: 'Trending unavailable',
    trendingDesc: 'Charts could not load right now. Check your connection and try again.',
    retry: 'Retry',
    chart: 'Chart · Updated daily',
    topIn: (country: string) => `Top 10 in ${country}`,
    topGlobal: 'Top 10 worldwide',
    showAll: 'Show all',
    playChart: 'Play chart',
    songs: (n: number) => `${n} songs`,
    newReleases: 'New from artists you play',
    artistsLike: 'Artists you might like',
    browseTag: (tag: string) => tag,
    emptyTasteDesc: 'Play a few songs you love — Discover fills in from there.',
    chartArtists: 'Artists on the charts',
    releaseMeta: (artist: string, date: string) => `${artist} · ${date}`,
    playRelease: 'Play album',
    charts: 'Charts',
    spotlight: 'Spotlight',
    onTheCharts: 'On the charts now',
    movingNow: 'Moving now',
    playSpotlight: 'Play',
    openWorld: 'Open',
  },
  profileHub: {
    favoritesTitle: 'Your Favorite Library',
    favoritesCount: (n: number) => (n === 1 ? '1 Song' : `${n} Songs`),
    playlistsTitle: 'Your Playlist Collections',
    createNew: 'Create New',
    backToPlaylists: 'Back to Playlists',
  },
  stats: {
    tab: 'Your sound',
    thisWeek: 'This week',
    thisMonth: 'Last 30 days',
    streak: (n: number) => (n === 1 ? '1-day streak' : `${n}-day streak`),
    yourNumberOne: 'Your #1',
    topArtists: 'Top artists',
    topTracks: 'Top tracks',
    listeningClock: 'Listening clock',
    peakHour: (hour: string) => `Most plays around ${hour}`,
    plays: (n: number) => (n === 1 ? '1 play' : `${n} plays`),
    noRankings: 'Not enough listens yet.',
    emptyTitle: 'Your sound is empty',
    emptyBody: 'Play a few songs — minutes, rankings, and Replay show up here.',
    replayEyebrow: 'NOIR Replay',
    replayHint: 'Last month, as five Bone cards.',
    openReplay: 'Open Replay',
    closeReplay: 'Close Replay',
    replayPrev: 'Back',
    replayNext: 'Next',
    replayDone: 'Done',
    saveImage: 'Save image',
  },
  greeting: {
    morning: 'Good morning',
    afternoon: 'Good afternoon',
    evening: 'Good evening',
    lateNight: 'Late night',
  },
  tour: {
    searchTitle: 'Search anything',
    searchDesc: 'Find songs, artists, or paste a YouTube link. You can also upload local audio from the home screen.',
    discoverTitle: 'Discover',
    discoverDesc: 'Trending charts and daily picks live here. Scroll down or use the section dots on the right.',
    navTitle: 'Quick navigation',
    navDesc: 'Jump between Home, Discover, and My Hub. Favorites, playlists, and your profile live in My Hub.',
    completed: 'You\'re all set!',
    completedDesc: 'Search a track or explore Discover to get started.',
  },
} as const;
